name: nexora_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencies for UI and functionality
  smooth_page_indicator: ^1.0.0+2      # Page indicators for onboarding
  flutter_native_splash: ^2.2.18       # Generates splash screen
  image_picker: ^1.1.2                 # Pick images from gallery/camera
  google_fonts: ^6.2.1                 # Google Fonts for typography
  flutter_launcher_icons: ^0.14.1      # For app launcher icons
  url_launcher: ^6.3.1                 # Opens URLs in a browser
  file_picker: ^8.1.3                  # File picker for documents/files
  geolocator: ^13.0.1                  # Access device geolocation
  shared_preferences: ^2.3.2           # Local storage for simple data

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/logo.png"           # Main app icon
  adaptive_icon_background: "#ffffff"              # Android adaptive icon bg
  adaptive_icon_foreground: "assets/app_icon/icon.png"  # Adaptive icon fg

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Core assets
    - assets/logo.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    - assets/placeholder.png
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/empty_notifications.png
    
    # Additional assets for user flow images
    - assets/forgot_password_image.png
    - assets/new_password_image.png
    - assets/password_reset_success_image.png
    - assets/setup_profile_image.png
    
    # Avatar images for user profiles
    - assets/avatars/avatar1.png
    - assets/avatars/avatar2.png
    - assets/avatars/avatar3.png
    - assets/avatars/avatar4.png
    - assets/avatars/avatar5.png

  # Font family definitions
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf         # Regular
        - asset: assets/fonts/Poppins-Bold.ttf            # Bold
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf          # Italic
          style: italic
