name: nexora_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  smooth_page_indicator: ^1.0.0+2  # Smooth page indicators for onboarding
  flutter_native_splash: ^2.2.18  # Custom splash screen generation
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.1
  url_launcher: ^6.3.1
  file_picker: ^8.1.3
  geolocator: ^13.0.1
  shared_preferences: ^2.3.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/logo.png"  # Path to your icon image (should be 512x512 or 1024x1024)
  adaptive_icon_background: "#ffffff"     # Optional for Android adaptive icons
  adaptive_icon_foreground: "assets/app_icon/icon.png"  # Optional

    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    - assets/placeholder.png
    - assets/google_logo.png
    - assets/facebook_logo.png
    - assets/empty_notifications.png
    - assets/forgot_password_image.png
    - assets/new_password_image.png
    - assets/password_reset_success_image.png
    - assets/setup_profile_image.png
    - assets/avatars/avatar1.png
    - assets/avatars/avatar2.png
    - assets/avatars/avatar3.png
    - assets/avatars/avatar4.png
    - assets/avatars/avatar5.png

# Define custom fonts
  fonts:
    - family: Poppins  # Font family name
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf  # Regular font style
        - asset: assets/fonts/Poppins-Bold.ttf     # Bold font style
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf   # Italic font style
          style: italic